import type { Product } from './types'

export const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL'] as const

function stockAll(n: number): Record<string, number> {
  return Object.fromEntries(SIZES.map((s) => [s, n]))
}

/** Seed catalog — admin can edit stock/prices; changes persist in localStorage. */
export const SEED_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Amara Satin Dress',
    slug: 'amara-satin-dress',
    price: 48500,
    oldPrice: 62000,
    category: 'Dresses',
    color: 'Rose',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85',
    badge: 'Bestseller',
    description:
      'A fluid satin midi with a soft drape and flattering waist. Made for Lagos evenings and celebrations that call for quiet confidence.',
    sizes: [...SIZES],
    stock: stockAll(12),
    barcode: 'BIC-DRS-001',
    reorderPoint: 4,
    active: true,
  },
  {
    id: 2,
    name: 'Lagos Linen Co-ord',
    slug: 'lagos-linen-coord',
    price: 42000,
    oldPrice: 0,
    category: 'Sets',
    color: 'Cream',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85',
    badge: 'New',
    description:
      'Breathable linen two-piece set with relaxed tailoring. Transition from daytime errands to dinner without changing your energy.',
    sizes: [...SIZES],
    stock: stockAll(8),
    barcode: 'BIC-SET-002',
    reorderPoint: 3,
    active: true,
  },
  {
    id: 3,
    name: 'The Zuri Slip Skirt',
    slug: 'zuri-slip-skirt',
    price: 29500,
    oldPrice: 0,
    category: 'Skirts',
    color: 'Chocolate',
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a13d27?auto=format&fit=crop&w=900&q=85',
    badge: 'Trending',
    description:
      'Bias-cut slip skirt that moves with you. Pair with a structured blouse or a soft knit for day-to-night polish.',
    sizes: [...SIZES],
    stock: stockAll(15),
    barcode: 'BIC-SKT-003',
    reorderPoint: 5,
    active: true,
  },
  {
    id: 4,
    name: 'Nia Draped Blouse',
    slug: 'nia-draped-blouse',
    price: 27500,
    oldPrice: 35000,
    category: 'Tops',
    color: 'Ivory',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=85',
    badge: 'Sale',
    description:
      'Soft draped blouse with clean lines and an easy neckline. The kind of top that makes everything else in your wardrobe work harder.',
    sizes: [...SIZES],
    stock: stockAll(10),
    barcode: 'BIC-TOP-004',
    reorderPoint: 4,
    active: true,
  },
  {
    id: 5,
    name: 'Adaeze Evening Gown',
    slug: 'adaeze-evening-gown',
    price: 89000,
    oldPrice: 0,
    category: 'Dresses',
    color: 'Emerald',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85',
    badge: 'New',
    description:
      'Floor-length gown with a sculpted bodice and flowing skirt. Designed for black-tie moments and nights you will remember.',
    sizes: [...SIZES],
    stock: stockAll(6),
    barcode: 'BIC-DRS-005',
    reorderPoint: 2,
    active: true,
  },
  {
    id: 6,
    name: 'Kemi Wide-Leg Jumpsuit',
    slug: 'kemi-wide-leg-jumpsuit',
    price: 52000,
    oldPrice: 0,
    category: 'Jumpsuits',
    color: 'Black',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85',
    badge: 'Bestseller',
    description:
      'One-and-done elegance. Wide-leg jumpsuit with a defined waist and refined shoulder — power dressing, softened.',
    sizes: [...SIZES],
    stock: { XS: 2, S: 3, M: 5, L: 4, XL: 2, XXL: 1 },
    barcode: 'BIC-JMP-006',
    reorderPoint: 3,
    active: true,
  },
  {
    id: 7,
    name: 'Ife Wrap Top',
    slug: 'ife-wrap-top',
    price: 24500,
    oldPrice: 0,
    category: 'Tops',
    color: 'Terracotta',
    image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=85',
    badge: '',
    description:
      'Flattering wrap silhouette in a warm terracotta tone. Works under blazers or alone with high-waisted trousers.',
    sizes: [...SIZES],
    stock: stockAll(14),
    barcode: 'BIC-TOP-007',
    reorderPoint: 4,
    active: true,
  },
  {
    id: 8,
    name: 'Chioma Pleated Set',
    slug: 'chioma-pleated-set',
    price: 58000,
    oldPrice: 72000,
    category: 'Sets',
    color: 'Champagne',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=85',
    badge: 'Sale',
    description:
      'Matching pleated top and skirt set with a luminous finish. Wedding guest energy, elevated everyday optional.',
    sizes: [...SIZES],
    stock: stockAll(7),
    barcode: 'BIC-SET-008',
    reorderPoint: 3,
    active: true,
  },
  {
    id: 9,
    name: 'Bola Midi Dress',
    slug: 'bola-midi-dress',
    price: 39500,
    oldPrice: 0,
    category: 'Dresses',
    color: 'Navy',
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85',
    badge: 'Trending',
    description:
      'Structured midi with a soft neckline and easy fit through the hip. Office-to-evening without the outfit change.',
    sizes: [...SIZES],
    stock: stockAll(11),
    barcode: 'BIC-DRS-009',
    reorderPoint: 4,
    active: true,
  },
  {
    id: 10,
    name: 'Sade Pencil Skirt',
    slug: 'sade-pencil-skirt',
    price: 26500,
    oldPrice: 0,
    category: 'Skirts',
    color: 'Charcoal',
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a13d27?auto=format&fit=crop&w=900&q=85',
    badge: '',
    description:
      'Classic pencil skirt with a modern stretch. Back vent for movement, clean finish for boardrooms and brunches.',
    sizes: [...SIZES],
    stock: { XS: 0, S: 1, M: 2, L: 3, XL: 2, XXL: 1 },
    barcode: 'BIC-SKT-010',
    reorderPoint: 5,
    active: true,
  },
  {
    id: 11,
    name: 'Yetunde Utility Jumpsuit',
    slug: 'yetunde-utility-jumpsuit',
    price: 45500,
    oldPrice: 0,
    category: 'Jumpsuits',
    color: 'Olive',
    image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=85',
    badge: 'New',
    description:
      'Utility-inspired jumpsuit softened with a feminine cut. Pockets that actually work, silhouette that actually flatters.',
    sizes: [...SIZES],
    stock: stockAll(9),
    barcode: 'BIC-JMP-011',
    reorderPoint: 3,
    active: true,
  },
  {
    id: 12,
    name: 'Temi Cropped Blazer Set',
    slug: 'temi-cropped-blazer-set',
    price: 67500,
    oldPrice: 0,
    category: 'Sets',
    color: 'Sand',
    image: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=900&q=85',
    badge: 'Bestseller',
    description:
      'Cropped blazer and tailored trousers in a warm sand tone. The set that makes “I have nothing to wear” obsolete.',
    sizes: [...SIZES],
    stock: stockAll(5),
    barcode: 'BIC-SET-012',
    reorderPoint: 2,
    active: true,
  },
]

export const CATEGORY_META: { name: Product['category'] | 'All'; countLabel: string; image: string }[] = [
  { name: 'Dresses', countLabel: 'styles', image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85' },
  { name: 'Tops', countLabel: 'styles', image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=85' },
  { name: 'Sets', countLabel: 'styles', image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=85' },
  { name: 'Jumpsuits', countLabel: 'styles', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85' },
]

export function totalStock(product: Product): number {
  return Object.values(product.stock).reduce((a, b) => a + b, 0)
}

export function isLowStock(product: Product): boolean {
  return totalStock(product) <= product.reorderPoint
}
